// Shared synthetic feedback corpus for the AIDISA demo.
// Raw channel text (WhatsApp transcripts, emails, call notes, web forms,
// social posts) modelled on real feedback patterns. All names and numbers are
// made up. {t}, {t1}.. and {d} tokens are filled with the report's time/date.
// Used by the portal (app.js) and the sentiment dashboard (dashboard.js).
(function () {
  "use strict";
  var S = {};

  S.seeds = [
    ["Escalator speeds up", "[{t}, {d}] +65 **** : Orchard station escalator suddenly sped up when I stepped on it\n[{t1}, {d}] +65 **** : Almost lost my footing. Pls check\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "Orchard MRT", 8, "WhatsApp (SNAP)"],
    ["Announcements overlap", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nAt Upper Thomson MRT, the announcement for platform A and platform B play at the same time. Cannot hear either one clearly. This has been happening since last year, I told the counter staff already.\n\nRegards,\nMr Ong", "Upper Thomson MRT", 18, "Email"],
    ["Burning smell this morning", "[{t}, {d}] +65 **** : Got burning smell every time the MRT stops at a station\n[{t1}, {d}] +65 **** : Faded after a few stops but others noticed also\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "North South Line", 31, "WhatsApp (SNAP)"],
    ["Thank you for helping me", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nI felt giddy and nauseous on the train and got off at Yio Chu Kang. A staff member brought me a wheelchair and water and made sure I was ok before I left. Thank you very much, please pass my compliments to him.\n\nRegards,\nMdm Goh", "Yio Chu Kang MRT", 55, "Email"],
    ["Gantry cannot read phone", "Woodlands tel gantry cannot read my phone leh, have to ask staff open for me. works fine at other stns. pls fix 🙏", "Woodlands MRT", 95, "Social Media"],
    ["Concession top-up question", "CSR note: Pax called in to ask if concession card can be topped up at the passenger service counter. Pax's daughter was told No on 9 Feb but the next day another staff said yes. Pax wants a clear answer and an explanation why the daughter was turned away.", "Admiralty MRT", 180, "Phone (CSR note)"],
    ["Water dripping on panel", "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Water seepage\nIncident station : HAVELOCK\nIncident date : {d}\nIncident time : {t}\nMessage : Water seepage into the station and onto the info panel, splashing onto people who are in front of the panel looking for directions. Floor below is wet, danger to elderly.", "Havelock MRT", 420, "Web Form"],
    ["Lost black cold bag", "[{t}, {d}] +65 **** : Hi, left my black rectangular cold bag on the train to Khatib last night\n[{t}, {d}] +65 **** : Got food and wallet inside\n[{t3}, {d}] SMRT SNAP REP: We are sorry to learn that you have lost your item. Please allow me to refer your feedback to a Customer Relations Officer who will reach out to you.", "Sembawang MRT", 900, "WhatsApp (SNAP)"]
  ];

  // Occasional incidents mixed into the live feed. Written as raw channel
  // text (WhatsApp transcripts, emails, call notes) with {t}/{d} tokens
  // that are filled in with the time the report is received.
  S.incidents = [
    { title: "Door closed on stroller", description: "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Train door\nIncident station : TAI SENG\nIncident date : {d}\nIncident time : {t}\nMessage : Train door closed on a lady with a stroller, she was nearly dragged. Staff came and helped, baby ok but mum very shaken.", source_at: "Web Form", incident_at: "Tai Seng MRT" },
    { title: "Lift not working", description: "[{t}, {d}] +65 **** : Hi, one of the lift button (going up) is not working\n[{t}, {d}] +65 **** : Lift fault at woodlands tel. Lift ended up not moving\n[{t1}, {d}] +65 **** : We were stuck in it for a while as the lift went up and came down on its own\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", source_at: "WhatsApp (SNAP)", incident_at: "Woodlands MRT" },
    { title: "Burning smell on train", description: "[{t}, {d}] +65 **** : Hi we passenger's smelt a burning smell earlier in train 1122\n[{t}, {d}] +65 **** : Boarded at Sembawang. Now at yishun\n[{t1}, {d}] +65 **** : Smell reduced a bit now but can still smell it. Maybe a component got burnt somewhere\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", source_at: "WhatsApp (SNAP)", incident_at: "North South Line" },
    { title: "Water dripping on seat", description: "[{t}, {d}] +65 **** : Window seal leak, causing water to accumulate on the seat.\n[{t}, {d}] +65 **** : Water leak on the 2nd seat from 2nd door, Train 1076\n[{t2}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.\n[{t3}, {d}] +65 **** : Hope this pic helps", source_at: "WhatsApp (SNAP)", incident_at: "East West Line" },
    { title: "Trains stopped - track fault", description: "wah train stop again between stns. captain say track fault. everybody late for work again sia #SMRT #nsl", source_at: "Social Media", incident_at: "Yishun MRT" },
    { title: "Unattended bag at gantry", description: "CSR note: Pax called in to report an unattended bag next to the fare gates at Raffles Place. Pax says it has been there for about an hour and nobody claimed it. Pax is worried and wants station staff to check.", source_at: "Phone (CSR note)", incident_at: "Raffles Place MRT" },
    { title: "Passenger fainted in cabin", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nA lady fainted in the crowded cabin between Queenstown and Redhill. Some passengers pressed the emergency button. Station staff came quickly, supported her and everything was done in a minute or two. Just want to say well done to your staff.\n\nRegards,\nMr Wong", source_at: "Email", incident_at: "East West Line" },
    { title: "Escalator jerk", description: "[{t}, {d}] +65 **** : Esplanade Exit F up escalator\n[{t}, {d}] +65 **** : Got escalator jerk to full speed, old uncle almost fell\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", source_at: "WhatsApp (SNAP)", incident_at: "Esplanade MRT" },
    { title: "RIMS - passenger fell on escalator", description: "Hi CR Colleagues,\n\nThere was a case of pax that fell on the escalator this evening at approx. {t} in Great World station. Pax was attended to by station staff with first aid and conveyed to SGH by ambulance. RIMS report has been raised.\n\n-----Original Message-----\nSubject: RIMS case has been sent to you / your organisation. Passenger fell at Escalator B2E04\n\nCase type: Incident - Train - Accident and sickness\nStatus: Registered\n\nCase description: At {t} passenger fell on the escalator while trying to retrieve his bag of groceries. Injuries sustained on the left side of head (bleeding). Pax complained of pain on his left hand. First aid was administered for his head injury. Pax was brought to the first aid room for resting. Ambulance was activated by station staff and arrived about 20 minutes later. Pax was conveyed to SGH. Pax's wife was with him throughout the incident but did not follow him to SGH.\n\nLocation: Train Station - TEL - Great World\nHow revealed: Passenger\nAuthorities notified: Duty Station Operation Manager, Singapore Civil Defence Force\n\nFor your follow up please.\n\nBest Regards,\nService Operations Manager", source_at: "Station Report", incident_at: "Great World MRT" },
    { title: "MSO - water leak, slippery walkway", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT Corporation,\n\nThe Municipal Services Office (MSO) has received feedback from a member of public as follows. We would appreciate it if the SMRT Corporation management could look into the matter and update MSO at ****@***.** on your follow-up actions for our records, please.\n\n(Note: This email may contain sensitive information related to the feedback. We urge you to use the information with discretion, especially when relaying the information of the case to a third party, e.g. contractors/service providers.)\n\nIncident Description\n\n“This has been going on for quite a long time. Water leak from the wall near the exit causing the walkway to become slippery. The current solution of blocking the gap at the bottom of the wall with towels is obviously not working at all. This morning an office lady in heels nearly slipped and I had to grab her arm. The cleaner just put a yellow sign and walked off. Please stop the leak from the source, not just mop mop every day.”\n\nTime and Date of Incident\n\n{d} {t}\n\nIncident Location\n\nHavelock MRT Station, Exit 5 linkway\n\nPicture(s)\n\nPlease see attached.\n\nThank you.\n\nYours Sincerely,\n\nOfficer (Mr)\nMunicipal Services Office, Ministry of National Development", source_at: "Email", incident_at: "Havelock MRT" },
    { title: "Train door - complaint, please log", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear Sir/Madam,\n\nPlease log this as a COMPLAINT, not feedback, as this is about a safety issue.\n\nEvery day when I change from the EW line to the NS line at Jurong East, I see commuters running to board the train at the opposite platform. The train door starts closing while people are still stepping in. This evening around {t} the train door closed on a man's arm and he had to pull it out. There was no staff on the platform at that moment.\n\nI cannot understand why it is not possible to have better coordination so that people alighting have time to walk to the other platform. With commuters dashing in when the doors are closing, it is like waiting for an accident to happen. Where is the safe and seamless journey that you show on your advertisement board?\n\nI hope to see changes made quickly and that the daily journey is no longer a heart-attack event.\n\nThank you.\nMr Ho", source_at: "Email", incident_at: "Jurong East MRT" }
  ];

  // Everyday feedback - deliberately free of incident phrases.
  S.routines = [
    { title: "Wallet returned", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nI would like to thank the station staff who called me within the hour to say my wallet was found. I lost it on the train from Woodlands and thought confirm gone. Everything was inside, even the cash. Please pass my thanks to them.\n\nRegards,\nMdm Lee", source_at: "Email", incident_at: "Woodlands MRT" },
    { title: "Announcement too loud early morning", description: "[{t}, {d}] +65 **** : Hello, I live near pioneer mrt station. It is 515am and the station will make announcements whenever a train passes by\n[{t}, {d}] +65 **** : Such announcements are not needed as the station is not open yet\n[{t1}, {d}] +65 **** : So please assist to stop these announcements in the morning\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", source_at: "WhatsApp (SNAP)", incident_at: "Pioneer MRT" },
    { title: "Cannot find the exit", description: "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Directions\nIncident station : BUONA VISTA\nIncident date : {d}\nIncident time : {t}\nMessage : I got out of the circle line and wanted to go through EWL exit. Followed the signs but cannot find the exit, walked around for 10 min. So confusing, pls improve your signage.", source_at: "Web Form", incident_at: "Buona Vista MRT" },
    { title: "Gantry doesnt read phone", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nMy phone NFC works at every other gantry but cannot tap in or out at the TEL stations. Using Xiaomi POCO X4. Pls kindly check, thanks.\n\nRegards,\nHui Min", source_at: "Email", incident_at: "Woodlands MRT" },
    { title: "Station manager helped us", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nWe are tourists. Das, your station manager at Dhoby Ghaut, brought us all the way to our exit with our heavy luggage and even gave us shelter from the rain. So helpful. Singapore is a wonderful place.\n\nRegards,\nGavin", source_at: "Email", incident_at: "Dhoby Ghaut MRT" },
    { title: "Charged full fare by mistake", description: "CSR note: Pax called in. Pax tapped in by mistake but did not take the train, tapped out at the same station and was charged the full fare. Staff told pax nothing can be done as it was a credit card. Pax wants to know how to appeal for a refund.", source_at: "Phone (CSR note)", incident_at: "Outram Park MRT" },
    { title: "No tissue in toilet", description: "Lavender stn toilet got no tissue again leh. All other stn also like that, why SMRT cannot refill? 🙄", source_at: "Social Media", incident_at: "Lavender MRT" },
    { title: "Photography question", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nI was filming a train at the platform and a security officer stopped me and told me to delete the video, saying it is against the law. Is it really not allowed? Many of us train enthusiasts do this. Please clarify.\n\nRegards,\nNoah", source_at: "Email", incident_at: "Buona Vista MRT" },
    { title: "Need seats near lift", description: "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Seats near lift landing\nIncident station : BUKIT GOMBAK\nIncident date : {d}\nIncident time : {t}\nMessage : Bukit Gombak MRT platform has no seats near the lift landing for the senior citizens. I filled up a form months ago and nobody called me back. Very disappointing.", source_at: "Web Form", incident_at: "Bukit Gombak MRT" },
    { title: "Staff helped with stroller", description: "[{t}, {d}] +65 **** : Just want to say thanks to the staff at Kallang\n[{t1}, {d}] +65 **** : He helped me pass my stroller thru the side gate, so patient", source_at: "WhatsApp (SNAP)", incident_at: "Kallang MRT" },
    { title: "Lost EZ-Link card", description: "[{t}, {d}] +65 **** : Hi, I lost my EZ link card on the circle line yesterday afternoon\n[{t3}, {d}] SMRT SNAP REP: We are sorry to learn that you have lost your item. Please allow me to refer your feedback to a Customer Relations Officer who will reach out to you. Alternatively, you can send us a report through our lost and found webform.", source_at: "WhatsApp (SNAP)", incident_at: "Circle Line" },
    { title: "Compliment - five staff over two weeks", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nHi,\n\nI wish to commend the following staff for their kind assistance and excellent service. I am a wheelchair user and travel daily.\n\n1. Staff at Woodlands Interchange\n- Encounter date/time: about 8.30 am\n- He took the initiative to approach me when he saw me struggling during the morning peak. He wheeled me to my bus berth and insisted on waiting with me until my bus came, even though I kept telling him there was no need.\n\n2. Staff at Yishun MRT station\n- Encounter date/time: about 2.30 pm\n- She promptly offered her help at the gantry, accompanied me to the platform and helped me board the train safely.\n\n3. Staff at Canberra MRT station (male, middle aged)\n- He greeted me at the linkbridge gantry and asked if I needed help. Although I did not, his friendliness lighted up my day.\n\n4. Staff at Canberra MRT station\n- She showed me a shorter way to the second platform from the linkbridge when I told her I always had to go down to street level first. She then accompanied me and helped me board.\n\n5. Staff at Admiralty MRT station\n- She patiently answered my questions during the morning peak and even offered to wheel me to my destination.\n\nPlease send my utmost gratitude to the above staff for their kindness, patience and willingness to help with a smile. Not all staff I met were so nice, especially during peak hours, which makes these five all the more special.\n\nOn a separate note, the signage for the lift at Canberra linkbridge is not very visible. Maybe can make it bigger.\n\nThank you\nMs Lim", source_at: "Email", incident_at: "North South Line" },
    { title: "Compliment - daughter separated on train", description: "I am a tourist from Taiwan. On {d} at around {t}, my six-year-old daughter rushed into the train at Dhoby Ghaut and I was not able to board together with her, so we were separated. She cannot speak English and is totally unfamiliar with Singapore. I was very anxious and terrified.\n\nI got off at Toa Payoh and a kind old lady accompanied me to the passenger service counter and helped translate. I left my number, my daughter's Chinese name and the colour of her clothes. Within ten minutes, the station called me: my daughter was safe at Somerset! Two kind passengers had brought her to the counter. The station manager comforted her in Mandarin, and another staff found her insurance card in her backpack to confirm her name. They even gave her a lollipop and a bottle of water while waiting for me.\n\nI am very grateful to the SMRT service team. Very efficient, during the busy evening peak, and I found my daughter within half an hour. This is the most memorable thing about my stay in Singapore. Thank you!\n\n我是来新加坡旅游的台湾人。我六岁的女儿在 Dhoby Ghaut 站先上了车，我来不及跟她一起上车，两个人就分开了。她听不懂也不会说英语，我非常着急。在 Toa Payoh 站一位好心的老婦人陪我去控制中心帮忙翻译。不到十分钟，地铁公司就打电话告诉我，女儿在 Somerset 站等我！站长用华语安抚她，还给她棒棒糖和一瓶水。由衷感谢新加坡地铁所有工作人员！", source_at: "Web Form", incident_at: "Somerset MRT" },
    { title: "Complaint - rude staff at counter", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\n Sent : {d} {t}\n Type : Feedback\n Division : Train\n Reply Type : Please reply\n Full name : Mr. ****\n Email address : ****@***.**\n Mobile number : ********\n Home number :\n Subject : Rude counter staff\n Train car number :\n Incident station : DOVER\n Incident date : {d}\n Incident time : {t}\n Boarding point : DOVER\n Alighting point : N/A\n Ez link card number : ********\n Message : Dear Sir/Mdm\n\nI am writing in with regards to your staff at the passenger service counter at Dover MRT.\n\nI was on my way to a wake and was not sure which direction to take, so I approached the counter. The staff was busy playing his handphone and I needed to say excuse me twice before he heard me.\n\nI asked him which direction to take the bus to Jurong East. He looked up irritated and asked 'which direction you going?' I said Jurong East. He said 'left'. I asked again, is that the bus stop?\n\nHe said, quote: 'Common sense can see!!!' unquote.\n\nHello, is this the way to answer the public? Even if I interrupt your games, you can just point and I will be happy to move on. When I told him he should be more polite, he said he is not wrong.\n\nWhat is the inquiry counter for if not for people to ask for help? I walked off because it was pointless to argue. I hope the relevant people can look into this, as with this attitude he can stain the name of SMRT, whose other staff I have met have been very helpful.\n\nYours sincerely", source_at: "Web Form", incident_at: "Dover MRT" },
    { title: "WhatsApp - toilet closed, long chat", description: "[{t}, {d}] +65 **** : When is the toilet being able to open for the commuter to use?\n[{t}, {d}] +65 **** : Or are you closing it down deliberately to refrain it from public to use it?\n[{t1}, {d}] +65 **** : Pending for your response. Thanks\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. To facilitate our checks, please provide:\n\nStation name\n[{t4}, {d}] +65 **** : This premise is locked down by SMRT. Hence please get the station manager to explain this move\n[{t4}, {d}] +65 **** : He is accountable and responsible for this matter\n[{t5}, {d}] +65 **** : Hopefully I do not need to go to the extent of finding out who is the station manager for this station, do I?\n[{t6}, {d}] +65 **** : Yishun. The one near exit A. Closed since June last year, now the notice say complete by end Jan. Got so much work to do meh?\n[{t6}, {d}] +65 **** : Senior citizens like me cannot hold so long one leh. Other stations all open\n[{t7}, {d}] +65 **** : Pending for your swift response. Tks\n[{t9}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", source_at: "WhatsApp (SNAP)", incident_at: "Yishun MRT" },
    { title: "Suggestion - bus and train timing", description: "Hi I have noticed the change of your train timing from 2316 to 2318 at Bedok towards Tuas on 27 and 28 Feb.\n\nThis has caused me inconvenience as I always take the 2nd last bus 93 at Eunos which departs the interchange at 2320. I will normally catch it when the train reaches Eunos at 2321, but with the change the train reaches at 2323 and I might miss my 2nd last bus. The last bus is a 25 mins wait, and I already finish work very late.\n\nI understand there may be operational reasons, but can SMRT consider coordinating with the bus operator for the last few trains of the night? Many shift workers like me depend on this connection. It would be great if the train timing could be changed back to 2316, or if the bus could wait a few minutes.\n\nThx.", source_at: "Web Form", incident_at: "Eunos MRT" },
    { title: "Compliment - staff lent me money", description: "Sent : {d} {t}\nType : Compliment\nDivision : Train\nReply Type : Just for your information\nSubject : Compliment Station Manager\nIncident station : CALDECOTT\nIncident date : {d}\nIncident time : {t}\nMessage : My daughter (P6) forgot her wallet and had no money to top up her card. She went to the control station and the station manager kindly lent her $10 so she could get home. We have returned the money. We are very grateful, please pass our thanks to him.", source_at: "Web Form", incident_at: "Caldecott MRT" },
    { title: "Compliment - helped me find my son", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nI was separated from my 11 year old son at Dhoby Ghaut and asked the control station for help. The staff on duty took down his details and went through the CCTV patiently. When I found my son 20 minutes later and went back to tell him, he was still checking the footage. He said my son's safety was the most important thing.\n\nPlease extend my sincere appreciation to him for his kindness to a very worried mother.\n\nRegards,\nMdm Tan", source_at: "Email", incident_at: "Dhoby Ghaut MRT" },
    { title: "Compliment - umbrella", description: "This rainy evening my umbrella got jammed half open and I could not bring it on the train. The staff at the counter tried his best, then called the station manager, who tried also and in the end gave me his own new umbrella still in the box!! Thank you both, really went out of your way. 🙏 #SMRT", source_at: "Social Media", incident_at: "Jurong East MRT" },
    { title: "Compliment - wheelchair user", description: "[{t}, {d}] +65 **** : Hi, I am a wheelchair user, just want to say thank you to the staff at Kent Ridge\n[{t1}, {d}] +65 **** : Every morning he help me and other wheelchair and pram users to go in the lift first. Always cheerful, my son wave to him and he wave back\n[{t2}, {d}] +65 **** : Pls convey my thanks\n[{t4}, {d}] SMRT SNAP REP: Thank you for your kind words. We will share your compliment with our colleague.", source_at: "WhatsApp (SNAP)", incident_at: "Kent Ridge MRT" },
    { title: "Compliment - phone found", description: "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nHi,\n\nMy wife and I lost our mobile at Kent Ridge station around 8.45pm. When we called the number, a staff member answered and said he had it. He checked some photos on the phone to make sure we were the owners before handing it back. We were very happy with how quick and careful he was.\n\nThank you very much.\n\nRegards,\nRajesh", source_at: "Email", incident_at: "Kent Ridge MRT" },
    { title: "Compliment - tourist pass help", description: "Hello. My family and I received exceptional service from one of your staff. He explained the new cashless ticketing to us very clearly and helped us get the tourist pass. If not for him our trip would not have been so smooth. A job very well done, thank you!", source_at: "Web Form", incident_at: "Changi Airport MRT" },
    { title: "Compliment - smooth train ride", description: "Sent : {d} {t}\nType : Compliment\nDivision : Train\nReply Type : Just for your information\nSubject : Smooth ride today\nIncident station : MARSILING\nIncident date : {d}\nIncident time : {t}\nMessage : Every Monday I take the train at about 2.30pm. Today the ride was very smooth, no sudden braking, smooth acceleration, even stopping at stations was smooth although it was raining. So smooth I did not need to hold the handrail. Please compliment the train captain on duty, he/she takes the job seriously. Well done!", source_at: "Web Form", incident_at: "North South Line" },
    { title: "Compliment - uncle who greets us", description: "Want to compliment the uncle at Outram Park EWL platform near the stairs to NEL. He greets passengers every morning for years already. I never respond but his positivity really brightens my day, esp during covid time. Hope uncle stays healthy! 😊", source_at: "Social Media", incident_at: "Outram Park MRT" },
    { title: "Compliment - card found within an hour", description: "[{t}, {d}] +65 **** : Just want to say thanks\n[{t1}, {d}] +65 **** : Lost my EZ link card at Woodlands South yesterday, staff radioed the train and called me same night to say it was found at Outram\n[{t2}, {d}] +65 **** : Very steady and patient, knows the SOP well. Keep up the good job!\n[{t5}, {d}] SMRT SNAP REP: Thank you for your kind words. We will share your compliment with our colleague.", source_at: "WhatsApp (SNAP)", incident_at: "Woodlands South MRT" },
    { title: "Compliment - bag retrieved", description: "Accidentally left my tote bag on the train when I alighted at Bishan. The lady at customer service contacted her colleague immediately and I collected it at the next station. Whole thing done in 10 minutes. Thank you so much!", source_at: "Web Form", incident_at: "Bishan MRT" }
  ];

  // Clusters of near-simultaneous reports about the same incident.
  S.scenarios = [
    { keyword: "burning smell", location: "Buona Vista MRT", reports: [
      ["WhatsApp - burning smell on train", "[{t}, {d}] +65 **** : Hi\n[{t}, {d}] +65 **** : Heavy burning smell in the train that just left Buona Vista\n[{t}, {d}] +65 **** : 2nd cabin from the end\n[{t1}, {d}] SMRT SNAP REP: Thank you for letting us know. To facilitate our checks, please provide:\n\n4-digit train car no.\n[{t1}, {d}] +65 **** : Train before 1012 dunno the number la, I alr got off\n[{t2}, {d}] +65 **** : Me n another commuter left the train cos of the smell\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["WhatsApp - smell every time train stops", "[{t}, {d}] +65 **** : Train towards Jurong East now\n[{t}, {d}] +65 **** : Got burning smell every time the MRT stops at a station\n[{t1}, {d}] +65 **** : Others around me can smell it too leh, aunty beside me also keep covering nose\n[{t2}, {d}] SMRT SNAP REP: Thank you for letting us know. To facilitate our checks, please provide:\n\n4-digit train car no.\n[{t2}, {d}] +65 **** : Not sure which car, sorry. I'm in the middle cabin\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["[Feedback][Train] burning smell near the door", "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Burning smell in cabin\nIncident station : BUONA VISTA\nIncident date : {d}\nIncident time : {t}\nMessage : Hi, there is a strong burning smell near the door of my cabin heading to Jurong East. Not sure if its the brakes or the aircon. Pls check the train before something happens, thanks!!", "Web Form"],
      ["Burning smell, people leaving", "Eh the train got burning smell sia. Ppl are all getting down at next stn. No announcement leh, wat is going on?? #SMRT #EWL @SMRT_Singapore", "Social Media"],
      ["Email - burning smell, full account", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nI am writing about my trip this evening on the East West Line from Commonwealth towards Jurong East. I boarded at about {t} and I want to put on record exactly what happened because I am quite worried.\n\n1) Shortly after the train left Buona Vista, there was a burning smell in the second cabin from the end. At first I thought somebody's food, but it got stronger, like rubber or wires burning.\n\n2) At least 5 or 6 passengers noticed it. One aunty was coughing and an uncle asked loudly 'got smell or not?' Everybody said yes.\n\n3) There was NO announcement at all. The train just continued as normal and stopped at each station as usual.\n\n4) Me and another commuter got off at the next station and told the staff at the platform. He said he will inform the control centre but did not seem very concerned.\n\nI am not trying to make a big fuss but if there really is something burning on the train, passengers should be told what to do. Please let me know what you found after checking the train, and whether it is safe.\n\nThank you.\n\nRegards,\nMr Teo\n\nSent from my iPhone", "Email"],
      ["Burning smell getting worse", "[{t}, {d}] +65 **** : The burning smell is getting worse\n[{t}, {d}] +65 **** : Rear cabin my eyes starting to sting already\n[{t1}, {d}] +65 **** : Pls send someone la\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["Burning smell again today", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nI took the Jurong East bound train again this evening and there was a burning smell in the cabin again, same as what I reported last week. I was told someone will look into it but obviously nothing has changed.\n\nCan I know what you found? Cannot keep telling people it is fine when got smell.\n\nRegards,\nMr Lim", "Email"]
    ] },
    { keyword: "track fault", location: "North South Line", reports: [
      ["WhatsApp - train stuck", "[{t}, {d}] +65 **** : Hi smrt\n[{t}, {d}] +65 **** : What wrong with the mrt train and it stop so long for every station from yishun onwards\n[{t1}, {d}] +65 **** : Currently stuck in the train heading to admiralty station halfway on the track\n[{t1}, {d}] +65 **** : Captain just say track fault ahead. Pls kindly look into this as alot of people rushing for work\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["Track fault, no staff on platform", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nWriting in about this morning's Red line. There was a track fault between Yishun and Woodlands and NOBODY was at the platform to tell us what to do. I had to go up to the control station myself to ask.\n\nWhat is the point of having staff if they dont come out when got problem? Pls explain.\n\nRegards,\nMs Tan", "Email"],
      ["Bridging bus not coming", "CSR note: Pax called in. After the track fault announcement pax waited at the bus stop for more than 20 minutes for the free bridging bus, but it never came. Staff on site told pax they were not sure where the pick-up point is. Pax very angry, said 'how can like that one, so unorganised'. Pax wants someone to call back.\n\nPax words: 'Last time got proper arrangement, now just say go bus stop wait. I wait 20 min still no bus. Then train start running already nobody tell us. Aiyo.'", "Phone (CSR note)"],
      ["Announcement too vague", "[{t}, {d}] +65 **** : Announcement just say track fault only\n[{t}, {d}] +65 **** : How long ah? Nobody tell us anything\n[{t1}, {d}] +65 **** : We need to know to decide take bus or wait la\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.\n[{t4}, {d}] +65 **** : That's the standard reply right", "WhatsApp (SNAP)"],
      ["Fwd: Fwd: track fault this morning (from MP office)", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear Customer Relations,\n\nPlease see below feedback forwarded by the MP's office on this morning's disruption. Appreciate your investigation and a reply to the resident, copying us.\n\nThank you.\n\nManager, Community Partnership\nWARNING: Privileged/Confidential information may be contained in this message. If you are not the intended addressee, you must not copy, distribute or take any action in reliance thereon.\n\nFrom: MP Office <****@***.**>\nSent: {d} {t}\nTo: LTA Community Partnership <****@***.**>\nSubject: Fwd: Train issue again\n\nDear colleague,\n\nAnother resident wrote in about the North South Line. This is the third time in two weeks I am forwarding this kind of feedback. Do investigate and update me on the operator's performance and whether it warrants further action.\n\nWarmest regards\n\nBegin forwarded message:\n\nFrom: Resident <****@***.**>\nSubject: Train issue again\n\nSir, good morning. Today the train stop between Yishun and Admiralty for almost 25 minutes because of track fault. Inside the cabin very hot and packed, got elderly and pregnant lady standing. The announcement only said 'track fault, we apologise for the inconvenience' and repeat repeat, nobody tell us how long.\n\nWhen finally reach the station, there was no staff to guide us to the bridging bus. I asked one staff where the free bus is, he said go to the bus stop opposite, but the bus captain there said that one is normal service not shuttle. Wasted another 20 minutes.\n\nI am a daily commuter and I understand faults happen, but the communication is very poor. Please help us, sir.\n\nThank you\nResident of Yishun", "Email"],
      ["Late for work - track fault", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nBecause of the track fault today I missed my company transport pick up at CCK and was 45 mins late. My boss already queried me. Can SMRT provide a memo or proof that train got fault? Please reply by email.\n\nThanks\n\nRegards,\nNoor", "Email"],
      ["Taxi fare claim after track fault", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nTrain stopped and everyone told to alight at Sembawang because of track fault. Station was jam packed so I took a private hire to work, S$38.50 (receipt attached). Can I claim? My EZ-link transaction history cannot retrieve, system error.\n\nLooking forward to your reply.\n\nRegards,\nMs Noorliana", "Email"]
    ] },
    { keyword: "train door", location: "Jurong East MRT", reports: [
      ["Door closed on me", "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Train door closed suddenly\nIncident station : JURONG EAST\nIncident date : {d}\nIncident time : {t}\nMessage : Train door closed on me suddenly, nearly hit my elbow when I and another old woman were entering the train at Jurong East platform towards Bukit Batok. No beeping, no warning. Very dangerous if train door close on passengers without driver checking.", "Web Form"],
      ["Door closed on bag", "[{t}, {d}] +65 **** : Train door just closed on my bag at platform\n[{t}, {d}] +65 **** : Almost kena dragged!! 😡\n[{t1}, {d}] +65 **** : Pls check the door closing timing, so many ppl still going in\n[{t2}, {d}] SMRT SNAP REP: Thank you for letting us know. To facilitate our checks, please provide:\n\n4-digit train car no.\n[{t2}, {d}] +65 **** : 3685\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["Elderly nearly caught", "CSR note: Pax called in. Pax saw an elderly lady about 70 years old nearly caught when the train door closed while people were still boarding at Jurong East. Staff nearby quickly asked for the door to be reopened. Lady did not fall but looked shocked. Pax wants SMRT to look into why the train door closes so fast during peak hour. No RIMS case number.", "Phone (CSR note)"],
      ["Evening peak doors too fast", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nThe train door closes way too fast in the evening peak. Today at 6.15pm the train door hit about 3 of us at Jurong East. Everybody rushing, nobody got time to step in properly. Pls extend the door open time at busy stations like this.\n\nThank you.\n\nRegards,\nMr Chua", "Email"],
      ["Station incident report - train door", "Hi CR Colleagues,\n\nFor your follow up please. Details as below.\n\nOn {d} at approximately {t}, pax (female, about 70 years old, wearing white) approached the PSC at Jurong East to report that the train door closed on her while she was boarding at platform B towards Bukit Batok.\n\nPax claimed:\n- She was the 4th passenger in the queue and was stepping in when the train door closed on her left side.\n- She did not hear any door closing chime because of the crowd noise.\n- One of our station staff quickly signalled for the door to be reopened. Pax lost balance and sat down on the platform.\n- Pax has bruises on her left arm and hip. She declined an ambulance.\n\nFollow up action by staff:\nSM on duty apologised to pax and offered first aid and a rest at the first aid room. Pax rested for about 20 minutes and continued her journey. CCTV footage has been requested.\n\nPax does not wish to claim anything but would like to know (1) why the train door closed so quickly, and (2) whether the train captain checked the platform before closing.\n\nPax wants a reply.\n\nBest Regards,\nSM (Jurong East)\nEpax: ****", "Station Report"],
      ["Same spot, door not sensing", "again!!! train door hit me at JE platform B. this is the 3rd time this month. the door doesnt sense ppl at all or wat?? #SMRT #safetyfirst", "Social Media"],
      ["Student hit by door", "[{t}, {d}] +65 **** : Train door closed on a school kid at Jurong East\n[{t}, {d}] +65 **** : Train start moving before anyone check, luckily he managed pull out his bag\n[{t1}, {d}] +65 **** : Not ok la, pls look into\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"]
    ] },
    { keyword: "no aircon", location: "Circle Line", reports: [
      ["WhatsApp - car 8223", "[{t}, {d}] +65 **** : 8223\n[{t}, {d}] +65 **** : No aircon\n[{t}, {d}] +65 **** : Mrt. Circle line\n[{t}, {d}] +65 **** : Very hot. Now.\n[{t1}, {d}] +65 **** : No aircon\n[{t2}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.\n[{t3}, {d}] +65 **** : Please check\n[{t3}, {d}] +65 **** : Now going to botanic gardens", "WhatsApp (SNAP)"],
      ["Morning commute no aircon", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nDear Sir/Madam,\n\nThis morning on the Circle line from Serangoon, no aircon in the whole train. Peak hour so crowded, everybody sweating and fanning with their hands. Cannot breathe properly with mask also.\n\nIs the driver feeling cold or what? Hot like sauna. Pls do something. Thank you.\n\nRegards,\nTan", "Email"],
      ["Technician on board?", "[{t}, {d}] +65 **** : Hi\n[{t}, {d}] +65 **** : No aircon in this cabin and train is full\n[{t1}, {d}] +65 **** : There is a technician in the train. Maybe u can contact him\n[{t2}, {d}] SMRT SNAP REP: Thank you for letting us know. To facilitate our checks, please provide:\n\n4-digit train car no.\n[{t2}, {d}] +65 **** : 8123\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["Complained last week also", "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Same problem again\nIncident station : BISHAN\nIncident date : {d}\nIncident time : {t}\nMessage : No aircon on the Circle Line train again, 7.45am Serangoon to Bishan. I gave the same feedback last week and thought it was fixed. Other lines no such problem, only Circle line. Pls check ALL the trains and not just one.", "Web Form"],
      ["MSO - recurring no aircon on LRT", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT Corporation,\n\nThe Municipal Services Office (MSO) has received feedback from a member of public as follows. We would appreciate it if the SMRT Corporation management could look into the matter and update MSO at ****@***.** on your follow-up actions for our records, please.\n\n(Note: This email may contain sensitive information related to the feedback. We urge you to use the information with discretion, especially when relaying the information of the case to a third party, e.g. contractors/service providers.)\n\nIncident Description\n\n“Second time writing in. Took the train this afternoon, the cabin was packed with commuters and there was no aircon at all. Previously already gave feedback that the train is not cold, no improvement. Some people using the advertisement flyers as fans, quite funny but actually not funny lah. Elderly and young children in the cabin, very stuffy, I worried somebody will faint. Please check ALL your trains, not just the one I report. Also can let us know when the new trains are coming? Thank you.”\n\nTime and Date of Incident\n\n{d} {t}\n\nIncident Location\n\nAboard Circle Line train, Serangoon towards Bishan\n\nPicture(s)\n\nPlease see attached.\n\nThank you.\n\nYours Sincerely,\n\nOfficer (Ms)\nMunicipal Services Office, Ministry of National Development", "Email"],
      ["Sauna", "Circle line train no aircon again 🥵🥵 whole cabin kena BBQ la. fares go up but aircon cannot work?? @SMRT_Singapore", "Social Media"],
      ["Child feeling dizzy", "CSR note: Pax called in. Pax boarded the Circle Line at Paya Lebar with a 4 year old child. Pax says there was no aircon in the cabin, very stuffy, and the child felt dizzy and nearly vomited. Pax alighted at the next station and approached the passenger service counter. Pax wants to know if SMRT knows about this and what is being done.", "Phone (CSR note)"]
    ] },
    { keyword: "escalator fault", location: "Esplanade MRT", reports: [
      ["Escalator at Exit F", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nHi,\n\nCould someone check the escalator at Esplanade Exit F heading up to South Beach please? Escalator fault, it is slow when nobody on it and then jerks to full speed when you step on. I almost lost my footing today just getting on.\n\nThanks\nAloysius\n\nRegards,\nAloysius", "Email"],
      ["Almost lost my footing", "[{t}, {d}] +65 **** : Esplanade Exit F escalator going up\n[{t}, {d}] +65 **** : escalator fault la, it suddenly speed up when I step on\n[{t1}, {d}] +65 **** : Almost fall down, got baby stroller behind me\n[{t2}, {d}] SMRT SNAP REP: Thank you for letting us know. To facilitate our checks, please provide:\n\n4-digit train car no.\n[{t2}, {d}] +65 **** : Not train lah, its the escalator. Station name Esplanade\n[{t3}, {d}] SMRT SNAP REP: Thank you for letting us know. We will look into it.", "WhatsApp (SNAP)"],
      ["Dangerous for seniors", "Escalator fault at Esplanade exit F is dangerous for old folks n kids. It run damn fast suddenly. Pls fix before somebody kena hurt #SMRT", "Social Media"],
      ["Same escalator again", "Sent : {d} {t}\nType : Feedback\nDivision : Train\nReply Type : Please reply\nSubject : Escalator fault - 2nd time\nIncident station : ESPLANADE\nIncident date : {d}\nIncident time : {t}\nMessage : Escalator fault at the same exit again today around 8.20am. I reported it 2 weeks ago, nothing done? Pls check. It jerks to full speed when there is no one on it.", "Web Form"],
      ["MSO - escalator fault at Esplanade", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT Corporation,\n\nThe Municipal Services Office (MSO) has received feedback from a member of public as follows. We would appreciate it if the SMRT Corporation management could look into the matter and update MSO at ****@***.** on your follow-up actions for our records, please.\n\n(Note: This email may contain sensitive information related to the feedback. We urge you to use the information with discretion, especially when relaying the information of the case to a third party, e.g. contractors/service providers.)\n\nIncident Description\n\n“Could someone check why the escalator at Esplanade Exit F heading up to South Beach jerks to full speed from idle? I almost lost my footing today just getting on. This escalator fault has been happening for at least 2 weeks. I saw an elderly couple holding the handrail very tightly and the uncle nearly tripped at the bottom. There is no staff or sign nearby to warn people. Please stop the escalator or put up a notice until it is repaired, and inform me what action is taken.”\n\nTime and Date of Incident\n\n{d} {t}\n\nIncident Location\n\nEsplanade MRT Station, Exit F\n\nPicture(s)\n\nPlease see attached.\n\nThank you.\n\nYours Sincerely,\n\nAloysius (Mr)\nMunicipal Services Office, Ministry of National Development", "Email"],
      ["Staff did not know", "CSR note: Pax called in to complain that when she told the staff at Esplanade about the escalator fault, he did not seem to know about it and just told her to use the lift. Pax said she is a senior and the lift is far. Pax wants SMRT to check and call her back.", "Phone (CSR note)"],
      ["Please stop it", "CAUTION: This email originated from outside of SMRT. Do not click links or open attachments unless you recognise the sender and are expecting the content or attachment.\n\nDear SMRT,\n\nPlease stop the escalator at Esplanade Exit F until the escalator fault is repaired. It is a matter of time before someone falls and gets hurt. I have seen aunties holding on to the handrail with both hands.\n\nRegards,\nAnonymous", "Email"]
    ] }
  ];

  window.AIDISA_SAMPLES = S;
})();
